# Site
name: "qMRLab"
description: "Quantitative MRI under one umbrella"
meta_description: "qMRLab - Quantitative MRI under one umbrella"
logo: 'assets/images/logo.png'
favicon: 'assets/images/icon.png'
baseurl: 'https://qmrlab.github.io/website'
google_analytics: 'UA-46278016-1'
disqus: 'qMRLab-test'

# Authors
authors:
  Mathieau:
    name: Mathieau Boudreau
    display_name: Mathieau
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: emb6150@gmail.com
    git_name: mathieuboudreau
    web: none
    twitter: https://twitter.com/_mattboud
    description: "Author"
  Agah:
    name: Agah Karakuzu
    display_name: Agah
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: agahkarakuzu@gmail.com
    git_name: agahkarakuzu
    web: http://agahkarakuzu.github.io
    twitter: https://twitter.com/agahkarakuzu
    description: "Author"
  john:
    name: John
    display_name: John
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    git_name: mathieuboudreau
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown
highlighter: rouge
