# Site
name: "qMRLab"
description: "Quantitative MRI under one umbrella"
meta_description: "qMRLab - Quantitative MRI under one umbrella"
logo: 'assets/images/logo.png'
favicon: 'assets/images/icon.png'
baseurl: 'https://qmrlab.org'
google_analytics: 'UA-116897577-1'
disqus: 'qmrlab'

# Authors
authors:
  Mathieu:
    name: Mathieu Boudreau
    display_name: Mathieu Boudreau
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: emb6150@gmail.com
    git_name: mathieuboudreau
    web: none
    twitter: https://twitter.com/_mattboud
    description: "Author"
  Agah:
    name: Agah Karakuzu
    display_name: Agah Karakuzu
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: agahkarakuzu@gmail.com
    git_name: agahkarakuzu
    web: http://agahkarakuzu.github.io
    twitter: https://twitter.com/agahkarakuzu
    description: "Author"
  Tommy:
    name: Tommy Boshkovski
    display_name: Tommy Boshkovski
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: boshkovski.tommy@gmail.com
    git_name: TommyBoshkovski
    web: https://tommyboshkovski.wixsite.com/index
    twitter: https://twitter.com/TommyBoshkovski
    description: "Author"
  Juan:
    name: Juan Velázquez-Reyes
    display_name: Juan Velázquez-Reyes
    gravatar: fcf1e8d3a2717cf25e8ff0c2bd99b9a5
    email: velazquezrj2012@licifug.ugto.mx
    git_name: jvelazquez-reyes
    twitter: https://twitter.com/juan_velrey
    description: "Author"
  Nadia:
    name: Nadia Blostein
    display_name: Nadia Blostein
    gravatar: 38f1b71e307f8c3eb09c2719ae58bc5a
    email: nadiablostein@gmail.com
    git_name: NadiaBlostein
    twitter: https://twitter.com/BlosteinNadia
    description: "Author"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown
highlighter: rouge
