# Site
name: "Igor & Lida's Chronicles"
description: "Ongoing seminar series on my grandparents' life's work and love for poetry."
meta_description: "Igor & Lida's Chronicles"
logo: 'assets/images/logo.png'
favicon: 'assets/images/icon.png'
baseurl: 'https://igor-lida-chronicles.github.io'
google_analytics: 'UA-116897577-1'
disqus: 'igor-lida-chronicles'

# Authors
authors:
  Agah:
    name: Agah Karakuzu
    display_name: Agah Karakuzu
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: agahkarakuzu@gmail.com
    git_name: agahkarakuzu
    web: http://agahkarakuzu.github.io
    twitter: https://twitter.com/agahkarakuzu
    description: "Author"
  Nadia:
    name: Nadia Blostein
    display_name: Nadia Blostein
    gravatar: 38f1b71e307f8c3eb09c2719ae58bc5a
    email: nadiablostein@gmail.com
    git_name: NadiaBlostein
    twitter: https://twitter.com/BlosteinNadia
    description: "Author"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown
highlighter: rouge
